### Advanced Topics


In [1]:
import numpy as np

### Be careful while copying arrays


In [2]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics


In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([10,20,30,40])
a + b

array([11, 22, 33, 44])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [10]:
# Take the sine of all the values in a
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [11]:
a = np.ones((2,3))
print(a)

b = np.full((3,3), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


array([[6., 6., 6.],
       [6., 6., 6.]])

In [12]:
# Find the determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [13]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.min(stats)


1

In [15]:
np.max(stats, axis=1)

array([3, 6])

In [16]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [17]:
before  = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [18]:
#Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

Load Data from File

In [23]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[ 83  12  57 901  44 728 315  66 492 103 875  29 640 711  58 234 999 420
 137 888  76 501 319 654 222 945  11 390 808 145 672  53 287 910 401 777
  38 614 250  95 830 176 543 702  89 361 470 918 207 624  15 759 348 981
 432 120 667 804 299 556  73 911 164 483 275 690 852  34 719 266 598 940
 187 321 760  49 871 233 615 402 958 110 544 683  27 792 356 621 478 905
 141 537 264 889 350 714  96 460 823 199]


##### Boolean Masking and Advanced Indexing

In [24]:
(~((filedata > 50) & (filedata < 100)))

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [25]:
filedata > 50

array([ True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
#you can index with a list in Numpy

a = np.array([1,2,3,4,5,6,7,8])
a[[1,4,6]]

array([2, 5, 7])

In [30]:
a = np.arange(1,101).reshape(10,10)
print(a)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
