I am going to write first code for numpy

Load in Numpy

In [2]:
import numpy as np

Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get total size
a.nbytes

12

In [10]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
a[1, 5]

13

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
b[0,1,1]

4

In [19]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [20]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])