### Basic Operations on numpy array


In [14]:
import numpy as np

arr = np.arange(1,82)

print(arr)

matrix = arr.reshape(9,9)

print("\n Updated matrix \n",matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81]

 Updated matrix 
 [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [15]:
transposed = matrix.T

print("Transposed Matrix: \n", transposed)

Transposed Matrix: 
 [[ 1 10 19 28 37 46 55 64 73]
 [ 2 11 20 29 38 47 56 65 74]
 [ 3 12 21 30 39 48 57 66 75]
 [ 4 13 22 31 40 49 58 67 76]
 [ 5 14 23 32 41 50 59 68 77]
 [ 6 15 24 33 42 51 60 69 78]
 [ 7 16 25 34 43 52 61 70 79]
 [ 8 17 26 35 44 53 62 71 80]
 [ 9 18 27 36 45 54 63 72 81]]


In [19]:
matrix1 = np.arange(1,82).reshape(9,9)
matrix2 = np.arange(82,163).reshape(9,9)


In [21]:
print("Matrix1: \n", matrix1)
print("\nMatrix2: \n", matrix2)

Matrix1: 
 [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]

Matrix2: 
 [[ 82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108]
 [109 110 111 112 113 114 115 116 117]
 [118 119 120 121 122 123 124 125 126]
 [127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144]
 [145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162]]


### General Operations

In [27]:
print("Sum")
print(matrix1 + matrix2)
print("Substract")
print(matrix1 - matrix2)
print("Divide")
print(matrix1 / matrix2)
print("Multiply")
print(matrix1 * matrix2)


Sum
[[ 83  85  87  89  91  93  95  97  99]
 [101 103 105 107 109 111 113 115 117]
 [119 121 123 125 127 129 131 133 135]
 [137 139 141 143 145 147 149 151 153]
 [155 157 159 161 163 165 167 169 171]
 [173 175 177 179 181 183 185 187 189]
 [191 193 195 197 199 201 203 205 207]
 [209 211 213 215 217 219 221 223 225]
 [227 229 231 233 235 237 239 241 243]]
Substract
[[-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]
 [-81 -81 -81 -81 -81 -81 -81 -81 -81]]
Divide
[[0.01219512 0.02409639 0.03571429 0.04705882 0.05813953 0.06896552
  0.07954545 0.08988764 0.1       ]
 [0.10989011 0.11956522 0.12903226 0.13829787 0.14736842 0.15625
  0.16494845 0.17346939 0.18181818]
 [0.19       0.1980198  0.20588235 0.21359223 0.22115385 0.22857143
  

In [28]:
#printing specific rows 
row_1 = matrix[0]
row_2 = matrix[1]
print(row_1,"\n", row_2)

[1 2 3 4 5 6 7 8 9] 
 [10 11 12 13 14 15 16 17 18]


In [29]:
#printing specific columns 
col_1 = matrix[:,0]
col_2 = matrix[:,1]
print(col_1,"\n", col_2)

[ 1 10 19 28 37 46 55 64 73] 
 [ 2 11 20 29 38 47 56 65 74]


In [32]:
#slicing 
# First two rows
print(matrix[:2, :])
print('\n')
# Last two columns
print(matrix[:, 1:])

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


[[ 2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18]
 [20 21 22 23 24 25 26 27]
 [29 30 31 32 33 34 35 36]
 [38 39 40 41 42 43 44 45]
 [47 48 49 50 51 52 53 54]
 [56 57 58 59 60 61 62 63]
 [65 66 67 68 69 70 71 72]
 [74 75 76 77 78 79 80 81]]


In [ ]:
#accessing a single element 

print(matrix[0,8])

TypeError: 'numpy.ndarray' object is not callable