### Doing some experiment with np array

In [3]:
import numpy as np

In [4]:
array = np.array([20,10,40,90,80,50,70,30]) 

In [5]:
#sum of the list
sum = sum(array)
print(sum)

#max of the list
print(max(array))

#min of the list
print(min(array))

#sort in ascending order
sort_nums = sorted(array, reverse=False)
print(sort_nums)

#sort in descending order
sort_nums = sorted(array, reverse=True)
print(sort_nums)

#printing first 3 values
print(array[:3])

#printing last 3 values
print(array[-3:])

#printing every second element
print(array[::2])

390
90
10
[10, 20, 30, 40, 50, 70, 80, 90]
[90, 80, 70, 50, 40, 30, 20, 10]
[20 10 40]
[50 70 30]
[20 40 80 70]
